---
name: pip_audit

'on':
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '55 1 * * 2,4'

permissions:
  contents: read

jobs:
  pip_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv and setup python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: 3.13
          activate-environment: "true"
        env:
          UV_VENV_SEED: 1

      - name: Generate requirements
        run: |
          uv export --no-hashes --no-dev --format requirements-txt --output-file requirements.txt
          uv export --no-hashes --format requirements-txt --output-file dev-requirements.txt

      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 # v1.1.0
        with:
          inputs: requirements.txt dev-requirements.txt
...
